/* ============================================================
   DATOS CURIOSOS CATÓLICOS — "Dato del día"
   Hechos curiosos y útiles tomados de fuentes oficiales de la
   Iglesia (vatican.va, Catecismo de la Iglesia Católica y
   documentos del Concilio Vaticano II).
   ============================================================ */

export interface Curiosity {
  id: string;
  cat: string;
  ico: string;
  color: string;
  title: string;
  body: string;
  src: string;
  link?: string;
  /** Conmemoración litúrgica (día del santo) para resolver su biografía. */
  comm?: string;
  /** Fecha en que se recuerda al santo (subtítulo). */
  day?: string;
}

export const CURIOSITIES: Curiosity[] = [
  {
    id: 'biblia-73',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: '¿Cuántos libros tiene la Biblia católica?',
    body: 'La Biblia católica tiene 73 libros: 46 del Antiguo Testamento y 27 del Nuevo. Este canon fue fijado en los Concilios de Hipona (393) y Cartago (397) y confirmado solemnemente por el Concilio de Trento (1546).',
    src: 'vatican.va · Catecismo de la Iglesia Católica',
    link: 'https://www.vatican.va/archive/catechism_sp/index_sp.html',
  },
  {
    id: 'biblia-salmos',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: 'El salmo más largo y el más corto',
    body: 'En la numeración latina (Vulgata) el Salmo más largo es el Salmo 118, con 176 versículos, y el más corto es el Salmo 116, con solo 2 versículos. ¡Ambos alaban la misericordia y la fidelidad de Dios!',
    src: 'vatican.va · Sagrada Escritura',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'biblia-biblioteca',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: 'La Biblia es una biblioteca',
    body: 'La palabra "Biblia" viene del griego "biblía", que significa "libros". No es un solo libro sino una colección de 73 escritos, de géneros muy distintos (historia, poesía, profecía, cartas…), compuestos a lo largo de unos 1.500 años por muchos autores.',
    src: 'vatican.va · Sagrada Escritura',
    link: 'https://www.vatican.va/archive/catechism_sp/index_sp.html',
  },
  {
    id: 'biblia-vulgata',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: 'La traducción oficial: la Vulgata',
    body: 'San Jerónimo tradujo las Sagradas Escrituras al latín entre los años 392 y 405, dando origen a la "Vulgata" (la edición difundida por todos los pueblos). El Concilio de Trento la declaró la versión latina auténtica de la Iglesia.',
    src: 'vatican.va · San Jerónimo, Doctor de la Iglesia',
    link: 'https://www.vatican.va/archive/catechism_sp/index_sp.html',
  },
  {
    id: 'biblia-imprenta',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: 'El primer gran libro impreso',
    body: 'En 1455, Johannes Gutenberg imprimió su famosa Biblia de 42 líneas: es considerada el primer libro de gran tamaño producido con tipos móviles en Occidente y, hasta hoy, la Biblia sigue siendo el libro más editado de la historia.',
    src: 'vatican.va · Historia',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'biblia-revelacion',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: 'Escritura y Tradición van juntas',
    body: 'Según la Constitución "Dei Verbum" del Concilio Vaticano II, la Revelación divina llega a nosotros por la Sagrada Escritura y la Tradición: ambas "fluidas de la misma fuente" y tendentes al mismo fin. Por eso, la fe católica no se apoya solo en el libro.',
    src: 'vatican.va · Dei Verbum, 9',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651118_dei-verbum_sp.html',
  },
  {
    id: 'santo-francisco',
    cat: 'Santos',
    ico: '🙏',
    color: '#7B5CD6',
    title: 'Los estigmas de San Francisco',
    body: 'San Francisco de Asís recibió los estigmas —las llagas de Cristo— en el monte Alvernia, en 1224, mientras oraba con la cruz. Fue canonizado apenas dos años después, en 1228, por el Papa Gregorio IX.',
    src: 'vatican.va · Culto de los santos',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'santa-doctoras',
    cat: 'Santos',
    ico: '🙏',
    color: '#7B5CD6',
    title: 'Las primeras Doctoras de la Iglesia',
    body: 'En 1970, el Papa Pablo VI nombró a Santa Teresa de Jesús y a Santa Catalina de Siena las primeras mujeres Doctoras de la Iglesia. Se sumaron después Santa Teresa de Lisieux (1997) y Santa Hildegarda de Bingen (2012).',
    src: 'vatican.va · Declaraciones de doctores',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'santo-kolbe',
    cat: 'Santos',
    ico: '🙏',
    color: '#7B5CD6',
    title: 'El santo que pidió el lugar de otro',
    body: 'En Auschwitz, San Maximiliano Kolbe se ofreció a morir en lugar de un padre de familia condenado al búnker del hambre. Murió el 14 de agosto de 1941 y fue canonizado por San Juan Pablo II en 1982.',
    src: 'vatican.va · Causas de santos',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'santo-pedro',
    cat: 'Santos',
    ico: '🙏',
    color: '#7B5CD6',
    title: 'La tumba de San Pedro',
    body: 'Jesús dijo a Pedro: "Tú eres Pedro, y sobre esta piedra edificaré mi Iglesia" (Mt 16,18). Bajo el altar de la Basílica de San Pedro se halla la tumba venerada del Apóstol, cuya identidad fue anunciada en 1968 por el Papa Pablo VI.',
    src: 'vatican.va · Evangelio de Mateo',
    link: 'https://www.vatican.va/archive/catechism_sp/index_sp.html',
  },
  {
    id: 'santo-isidoro',
    cat: 'Santos',
    ico: '🙏',
    color: '#7B5CD6',
    title: 'El patrón de Internet',
    body: 'San Isidoro de Sevilla, arzobispo del siglo VII y autor de las "Etimologías" (una enciclopedia del saber de su tiempo), fue proclamado patrono de Internet y de los internautas por el Papa san Juan Pablo II.',
    src: 'vatican.va · Culto de los santos',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'vaticano-estado',
    cat: 'Vaticano',
    ico: '🇻🇦',
    color: '#2F6FBA',
    title: 'El Estado más pequeño del mundo',
    body: 'Con apenas 0,44 km², la Ciudad del Vaticano es el Estado más pequeño del mundo. Es el lugar donde reside el Papa como sucesor de San Pedro, cabeza del Colegio de los 118 electores que lo eligen.',
    src: 'vatican.va · Estado de la Ciudad del Vaticano',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'vaticano-guardia',
    cat: 'Vaticano',
    ico: '🇻🇦',
    color: '#2F6FBA',
    title: 'La Guardia Suiza Pontificia',
    body: 'La Guardia Suiza fue fundada en 1506 por el Papa Julio II y es el ejército más antiguo que sigue activo y, a la vez, el más pequeño del mundo: unos 135 hombres. Su uniforme, según la tradición, fue diseñado por Miguel Ángel.',
    src: 'vatican.va · Guardia Suiza Pontificia',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'vaticano-conclave',
    cat: 'Vaticano',
    ico: '🇻🇦',
    color: '#2F6FBA',
    title: '¿De dónde viene "cónclave"?',
    body: '"Cónclave" viene del latín "cum clave", "bajo llave": los cardenales electores quedan encerrados hasta elegir al nuevo Papa. Hoy la elección puede suceder incluso bajo lluvia de "fumata" blanca en la Capilla Sixtina.',
    src: 'vatican.va · Constitución apostólica sobre la elección del Papa',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'vaticano-basilica',
    cat: 'Vaticano',
    ico: '🇻🇦',
    color: '#2F6FBA',
    title: 'El mayor templo cristiano',
    body: 'La Basílica de San Pedro, cuya cúpula fue obra de Miguel Ángel (1546), es el mayor templo de la cristiandad y uno de los lugares más visitados del mundo. Puede albergar unas 60.000 personas de pie.',
    src: 'vatican.va · Basílica de San Pedro',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'conc-v2-numero',
    cat: 'Concilio Vaticano II',
    ico: '✝️',
    color: '#2E8B57',
    title: 'El 21º concilio ecuménico',
    body: 'El Vaticano II, convocado por san Juan XXIII el 25 de diciembre de 1961 y abierto en 1962, fue el 21º concilio ecuménico de la Iglesia. Lo clausuró el Papa Pablo VI en 1965. Produjo 16 documentos: 4 constituciones, 9 decretos y 3 declaraciones.',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/index_sp.htm',
  },
  {
    id: 'conc-v2-liturgia',
    cat: 'Concilio Vaticano II',
    ico: '✝️',
    color: '#2E8B57',
    title: 'La misa en la lengua de cada pueblo',
    body: 'La Constitución "Sacrosanctum Concilium" (1963) renovó la liturgia y, fiel a la tradición, permitió el uso de las lenguas del pueblo en la celebración de la Eucaristía, que hasta entonces se celebraba en latín.',
    src: 'vatican.va · Sacrosanctum Concilium',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19631204_sacrosanctum-concilium_sp.html',
  },
  {
    id: 'conc-v2-docs',
    cat: 'Concilio Vaticano II',
    ico: '✝️',
    color: '#2E8B57',
    title: 'Los documentos clave del Concilio',
    body: 'Las 4 constituciones del Vaticano II son "Lumen Gentium" (la Iglesia), "Dei Verbum" (la Revelación), "Sacrosanctum Concilium" (la liturgia) y "Gaudium et Spes" (la Iglesia en el mundo actual). Entre las declaraciones destaca "Nostra Aetate", sobre las religiones no cristianas.',
    src: 'vatican.va · Documentos conciliares',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/index_sp.htm',
  },
  {
    id: 'mag-rerum',
    cat: 'Magisterio',
    ico: '📜',
    color: '#C2443E',
    title: 'La primera encíclica social',
    body: '"Rerum Novarum" (1891), del Papa León XIII, es la primera gran encíclica sobre la condición obrera y el origen de la doctrina social de la Iglesia: defendió el trabajo, la justa remuneración y la dignidad del trabajador.',
    src: 'vatican.va · Rerum Novarum',
    link: 'https://www.vatican.va/content/leo-xiii/es/encyclicals/documents/hf_l-xiii_enc_15051891_rerum-novarum.html',
  },
  {
    id: 'mag-enciclica',
    cat: 'Magisterio',
    ico: '📜',
    color: '#C2443E',
    title: '¿Qué es una encíclica?',
    body: '"Encíclica" viene del griego "enkýklios", es decir, "circular": es una carta del Papa dirigida a los obispos de todo el mundo (y a los fieles) sobre temas de fe, moral o sociedad. Se llama por sus primeras palabras en latín.',
    src: 'vatican.va · Documentos pontificios',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'mag-laudato',
    cat: 'Magisterio',
    ico: '📜',
    color: '#C2443E',
    title: 'La encíclica de la casa común',
    body: '"Laudato si\'" (2015), del Papa Francisco, lleva por título las primeras palabras del "Cántico de las criaturas" de San Francisco de Asís ("Alabado seas"). Llama a cuidar la creación y a una ecología integral que no olvide al ser humano.',
    src: 'vatican.va · Laudato si\'',
    link: 'https://www.vatican.va/content/francesco/es/encyclicals/documents/papa-francesco_20150524_enciclica-laudato-si.html',
  },
  {
    id: 'mag-jp2',
    cat: 'Magisterio',
    ico: '📜',
    color: '#C2443E',
    title: 'El Papa de los santos',
    body: 'San Juan Pablo II canonizó a más personas que todos sus predecesores juntos: proclamó cerca de 500 santos y más de 1.300 beatos, recordándonos que la santidad es una llamada universal, también para los laicos de hoy.',
    src: 'vatican.va · Pontificado de Juan Pablo II',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
];