/* ============================================================
   DATOS CURIOSOS CATÓLICOS — "Dato del día"
   Hechos curiosos y útiles tomados de fuentes oficiales de la
   Iglesia (vatican.va, Catecismo de la Iglesia Católica y
   documentos del Concilio Vaticano II).
   ============================================================ */

export interface Curiosity {
  id: string;
  cat: string;
  ico: string;
  color: string;
  title: string;
  body: string;
  src: string;
  link?: string;
  /** Conmemoración litúrgica (día del santo) para resolver su biografía. */
  comm?: string;
  /** Fecha en que se recuerda al santo (subtítulo). */
  day?: string;
}

export const CURIOSITIES: Curiosity[] = [
  {
    id: 'biblia-73',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: '¿Cuántos libros tiene la Biblia católica?',
    body: 'La Biblia católica tiene 73 libros: 46 del Antiguo Testamento y 27 del Nuevo. Este canon fue fijado en los Concilios de Hipona (393) y Cartago (397) y confirmado solemnemente por el Concilio de Trento (1546).',
    src: 'vatican.va · Catecismo de la Iglesia Católica',
    link: 'https://www.vatican.va/archive/catechism_sp/index_sp.html',
  },
  {
    id: 'biblia-salmos',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: 'El salmo más largo y el más corto',
    body: 'En la numeración latina (Vulgata) el Salmo más largo es el Salmo 118, con 176 versículos, y el más corto es el Salmo 116, con solo 2 versículos. ¡Ambos alaban la misericordia y la fidelidad de Dios!',
    src: 'vatican.va · Sagrada Escritura',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'biblia-biblioteca',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: 'La Biblia es una biblioteca',
    body: 'La palabra "Biblia" viene del griego "biblía", que significa "libros". No es un solo libro sino una colección de 73 escritos, de géneros muy distintos (historia, poesía, profecía, cartas…), compuestos a lo largo de unos 1.500 años por muchos autores.',
    src: 'vatican.va · Sagrada Escritura',
    link: 'https://www.vatican.va/archive/catechism_sp/index_sp.html',
  },
  {
    id: 'biblia-vulgata',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: 'La traducción oficial: la Vulgata',
    body: 'San Jerónimo tradujo las Sagradas Escrituras al latín entre los años 392 y 405, dando origen a la "Vulgata" (la edición difundida por todos los pueblos). El Concilio de Trento la declaró la versión latina auténtica de la Iglesia.',
    src: 'vatican.va · San Jerónimo, Doctor de la Iglesia',
    link: 'https://www.vatican.va/archive/catechism_sp/index_sp.html',
  },
  {
    id: 'biblia-imprenta',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: 'El primer gran libro impreso',
    body: 'En 1455, Johannes Gutenberg imprimió su famosa Biblia de 42 líneas: es considerada el primer libro de gran tamaño producido con tipos móviles en Occidente y, hasta hoy, la Biblia sigue siendo el libro más editado de la historia.',
    src: 'vatican.va · Historia',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'biblia-revelacion',
    cat: 'Biblia',
    ico: '📖',
    color: '#C8973A',
    title: 'Escritura y Tradición van juntas',
    body: 'Según la Constitución "Dei Verbum" del Concilio Vaticano II, la Revelación divina llega a nosotros por la Sagrada Escritura y la Tradición: ambas "fluidas de la misma fuente" y tendentes al mismo fin. Por eso, la fe católica no se apoya solo en el libro.',
    src: 'vatican.va · Dei Verbum, 9',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651118_dei-verbum_sp.html',
  },
  {
    id: 'santo-francisco',
    cat: 'Santos',
    ico: '🙏',
    color: '#7B5CD6',
    title: 'Los estigmas de San Francisco',
    body: 'San Francisco de Asís recibió los estigmas —las llagas de Cristo— en el monte Alvernia, en 1224, mientras oraba con la cruz. Fue canonizado apenas dos años después, en 1228, por el Papa Gregorio IX.',
    src: 'vatican.va · Culto de los santos',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'santa-doctoras',
    cat: 'Santos',
    ico: '🙏',
    color: '#7B5CD6',
    title: 'Las primeras Doctoras de la Iglesia',
    body: 'En 1970, el Papa Pablo VI nombró a Santa Teresa de Jesús y a Santa Catalina de Siena las primeras mujeres Doctoras de la Iglesia. Se sumaron después Santa Teresa de Lisieux (1997) y Santa Hildegarda de Bingen (2012).',
    src: 'vatican.va · Declaraciones de doctores',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'santo-kolbe',
    cat: 'Santos',
    ico: '🙏',
    color: '#7B5CD6',
    title: 'El santo que pidió el lugar de otro',
    body: 'En Auschwitz, San Maximiliano Kolbe se ofreció a morir en lugar de un padre de familia condenado al búnker del hambre. Murió el 14 de agosto de 1941 y fue canonizado por San Juan Pablo II en 1982.',
    src: 'vatican.va · Causas de santos',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'santo-pedro',
    cat: 'Santos',
    ico: '🙏',
    color: '#7B5CD6',
    title: 'La tumba de San Pedro',
    body: 'Jesús dijo a Pedro: "Tú eres Pedro, y sobre esta piedra edificaré mi Iglesia" (Mt 16,18). Bajo el altar de la Basílica de San Pedro se halla la tumba venerada del Apóstol, cuya identidad fue anunciada en 1968 por el Papa Pablo VI.',
    src: 'vatican.va · Evangelio de Mateo',
    link: 'https://www.vatican.va/archive/catechism_sp/index_sp.html',
  },
  {
    id: 'santo-isidoro',
    cat: 'Santos',
    ico: '🙏',
    color: '#7B5CD6',
    title: 'El patrón de Internet',
    body: 'San Isidoro de Sevilla, arzobispo del siglo VII y autor de las "Etimologías" (una enciclopedia del saber de su tiempo), fue proclamado patrono de Internet y de los internautas por el Papa san Juan Pablo II.',
    src: 'vatican.va · Culto de los santos',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'vaticano-estado',
    cat: 'Vaticano',
    ico: '🇻🇦',
    color: '#2F6FBA',
    title: 'El Estado más pequeño del mundo',
    body: 'Con apenas 0,44 km², la Ciudad del Vaticano es el Estado más pequeño del mundo. Es el lugar donde reside el Papa como sucesor de San Pedro, cabeza del Colegio de los 118 electores que lo eligen.',
    src: 'vatican.va · Estado de la Ciudad del Vaticano',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'vaticano-guardia',
    cat: 'Vaticano',
    ico: '🇻🇦',
    color: '#2F6FBA',
    title: 'La Guardia Suiza Pontificia',
    body: 'La Guardia Suiza fue fundada en 1506 por el Papa Julio II y es el ejército más antiguo que sigue activo y, a la vez, el más pequeño del mundo: unos 135 hombres. Su uniforme, según la tradición, fue diseñado por Miguel Ángel.',
    src: 'vatican.va · Guardia Suiza Pontificia',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'vaticano-conclave',
    cat: 'Vaticano',
    ico: '🇻🇦',
    color: '#2F6FBA',
    title: '¿De dónde viene "cónclave"?',
    body: '"Cónclave" viene del latín "cum clave", "bajo llave": los cardenales electores quedan encerrados hasta elegir al nuevo Papa. Hoy la elección puede suceder incluso bajo lluvia de "fumata" blanca en la Capilla Sixtina.',
    src: 'vatican.va · Constitución apostólica sobre la elección del Papa',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'vaticano-basilica',
    cat: 'Vaticano',
    ico: '🇻🇦',
    color: '#2F6FBA',
    title: 'El mayor templo cristiano',
    body: 'La Basílica de San Pedro, cuya cúpula fue obra de Miguel Ángel (1546), es el mayor templo de la cristiandad y uno de los lugares más visitados del mundo. Puede albergar unas 60.000 personas de pie.',
    src: 'vatican.va · Basílica de San Pedro',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'conc-v2-numero',
    cat: 'Concilio Vaticano II',
    ico: '✝️',
    color: '#2E8B57',
    title: 'El 21º concilio ecuménico',
    body: 'El Vaticano II, convocado por san Juan XXIII el 25 de diciembre de 1961 y abierto en 1962, fue el 21º concilio ecuménico de la Iglesia. Lo clausuró el Papa Pablo VI en 1965. Produjo 16 documentos: 4 constituciones, 9 decretos y 3 declaraciones.',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/index_sp.htm',
  },
  {
    id: 'conc-v2-liturgia',
    cat: 'Concilio Vaticano II',
    ico: '✝️',
    color: '#2E8B57',
    title: 'La misa en la lengua de cada pueblo',
    body: 'La Constitución "Sacrosanctum Concilium" (1963) renovó la liturgia y, fiel a la tradición, permitió el uso de las lenguas del pueblo en la celebración de la Eucaristía, que hasta entonces se celebraba en latín.',
    src: 'vatican.va · Sacrosanctum Concilium',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19631204_sacrosanctum-concilium_sp.html',
  },
  {
    id: 'conc-v2-docs',
    cat: 'Concilio Vaticano II',
    ico: '✝️',
    color: '#2E8B57',
    title: 'Los documentos clave del Concilio',
    body: 'Las 4 constituciones del Vaticano II son "Lumen Gentium" (la Iglesia), "Dei Verbum" (la Revelación), "Sacrosanctum Concilium" (la liturgia) y "Gaudium et Spes" (la Iglesia en el mundo actual). Entre las declaraciones destaca "Nostra Aetate", sobre las religiones no cristianas.',
    src: 'vatican.va · Documentos conciliares',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/index_sp.htm',
  },
  {
    id: 'mag-rerum',
    cat: 'Magisterio',
    ico: '📜',
    color: '#C2443E',
    title: 'La primera encíclica social',
    body: '"Rerum Novarum" (1891), del Papa León XIII, es la primera gran encíclica sobre la condición obrera y el origen de la doctrina social de la Iglesia: defendió el trabajo, la justa remuneración y la dignidad del trabajador.',
    src: 'vatican.va · Rerum Novarum',
    link: 'https://www.vatican.va/content/leo-xiii/es/encyclicals/documents/hf_l-xiii_enc_15051891_rerum-novarum.html',
  },
  {
    id: 'mag-enciclica',
    cat: 'Magisterio',
    ico: '📜',
    color: '#C2443E',
    title: '¿Qué es una encíclica?',
    body: '"Encíclica" viene del griego "enkýklios", es decir, "circular": es una carta del Papa dirigida a los obispos de todo el mundo (y a los fieles) sobre temas de fe, moral o sociedad. Se llama por sus primeras palabras en latín.',
    src: 'vatican.va · Documentos pontificios',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },
  {
    id: 'mag-laudato',
    cat: 'Magisterio',
    ico: '📜',
    color: '#C2443E',
    title: 'La encíclica de la casa común',
    body: '"Laudato si\'" (2015), del Papa Francisco, lleva por título las primeras palabras del "Cántico de las criaturas" de San Francisco de Asís ("Alabado seas"). Llama a cuidar la creación y a una ecología integral que no olvide al ser humano.',
    src: 'vatican.va · Laudato si\'',
    link: 'https://www.vatican.va/content/francesco/es/encyclicals/documents/papa-francesco_20150524_enciclica-laudato-si.html',
  },
  {
    id: 'mag-jp2',
    cat: 'Magisterio',
    ico: '📜',
    color: '#C2443E',
    title: 'El Papa de los santos',
    body: 'San Juan Pablo II canonizó a más personas que todos sus predecesores juntos: proclamó cerca de 500 santos y más de 1.300 beatos, recordándonos que la santidad es una llamada universal, también para los laicos de hoy.',
    src: 'vatican.va · Pontificado de Juan Pablo II',
    link: 'https://www.vatican.va/content/vatican/es.html',
  },

  /* ---- Documentos de la Iglesia (encíclicas, constituciones, catequesis):
         contenido real tomado de las páginas oficiales del Vaticano. ---- */

  {
    id: 'doc-rerum',
    cat: 'Documentos',
    ico: '📜',
    color: '#1F5F8F',
    title: 'Rerum Novarum (1891)',
    body: 'Primera gran encíclica social del Papa León XIII. Nacida "sobre la situación de los obreros", denuncia que "los adelantos de la industria...; la acumulación de las riquezas en manos de unos pocos y la pobreza de la inmensa mayoría" abren la "contienda" que la Iglesia quiere dirimir "conforme a la verdad y la justicia". Defiende el derecho al salario justo y a la propiedad privada.',
    src: 'vatican.va · León XIII',
    link: 'https://www.vatican.va/content/leo-xiii/es/encyclicals/documents/hf_l-xiii_enc_15051891_rerum-novarum.html',
  },
  {
    id: 'doc-humanae',
    cat: 'Documentos',
    ico: '📜',
    color: '#1F5F8F',
    title: 'Humanae Vitae (1968)',
    body: 'Encíclica de Pablo VI sobre la regulación de la natalidad. Comienza: "El gravísimo deber de transmitir la vida humana ha sido siempre para los esposos, colaboradores libres y responsables de Dios Creador, fuente de grandes alegrías aunque algunas veces acompañadas de no pocas dificultades y angustias".',
    src: 'vatican.va · Pablo VI',
    link: 'https://www.vatican.va/content/paul-vi/es/encyclicals/documents/hf_p-vi_enc_25071968_humanae-vitae.html',
  },
  {
    id: 'doc-laudato',
    cat: 'Documentos',
    ico: '📜',
    color: '#1F5F8F',
    title: 'Laudato si’ (2015)',
    body: '"«Laudato si\', mi\' Signore» – «Alabado seas, mi Señor», cantaba san Francisco de Asís. En ese hermoso cántico nos recordaba que nuestra casa común es también como una hermana, con la cual compartimos la existencia, y como una madre bella que nos acoge entre sus brazos". Es la encíclica del Papa Francisco sobre el cuidado de la creación y la ecología integral.',
    src: 'vatican.va · Francisco',
    link: 'https://www.vatican.va/content/francesco/es/encyclicals/documents/papa-francesco_20150524_enciclica-laudato-si.html',
  },
  {
    id: 'doc-lumen',
    cat: 'Documentos',
    ico: '✝️',
    color: '#1F5F8F',
    title: 'Lumen Gentium (1964)',
    body: 'Constitución dogmática del Concilio Vaticano II sobre la Iglesia. Comienza: "Cristo es la luz de los pueblos; por eso este sacratísimo Sínodo, congregado en el Espíritu Santo, desea ardientemente iluminar a todos los hombres con la luz de Cristo". Presenta a la Iglesia como misterio, pueblo de Dios y comunión.',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19641121_lumen-gentium_sp.html',
  },
  {
    id: 'doc-famili',
    cat: 'Documentos',
    ico: '📜',
    color: '#1F5F8F',
    title: 'Familiaris Consortio (1981)',
    body: 'Exhortación apostólica de Juan Pablo II "sobre la misión de la familia cristiana en el mundo actual". Comienza: "La familia, en los tiempos modernos, ha sufrido quizá como ninguna otra institución la acometida de las transformaciones amplias, profundas y rápidas de la sociedad y de la cultura". La llama "Iglesia doméstica".',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/apost_exhortations/documents/hf_jp-ii_exh_19811122_familiaris-consortio.html',
  },
  {
    id: 'doc-gs',
    cat: 'Documentos',
    ico: '✝️',
    color: '#1F5F8F',
    title: 'Gaudium et Spes (1965)',
    body: 'Constitución pastoral del Concilio Vaticano II "sobre la Iglesia en el mundo actual". Su famoso comienzo: "Los gozos y las esperanzas, las tristezas y las angustias de los hombres de nuestro tiempo, sobre todo de los pobres y de cuantos sufren, son a la vez los gozos y las esperanzas, las tristezas y las angustias de los discípulos de Cristo".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651207_gaudium-et-spes_sp.html',
  },
  {
    id: 'doc-cat',
    cat: 'Documentos',
    ico: '📕',
    color: '#1F5F8F',
    title: 'Catecismo de la Iglesia Católica',
    body: 'Promulgado en 1992 por San Juan Pablo II, expone la fe de la Iglesia. Su primera catequesis recuerda que "Dios, infinitamente perfecto y bienaventurado en sí mismo, en un designio de pura bondad, ha creado libremente al hombre para hacerle partícipe de su vida bienaventurada".',
    src: 'vatican.va · Catecismo de la Iglesia Católica',
    link: 'https://www.vatican.va/archive/catechism_sp/index_sp.html',
  },
  {
    id: 'doc-pacem',
    cat: 'Documentos',
    ico: '📜',
    color: '#1F5F8F',
    title: 'Pacem in Terris (1963)',
    body: 'Encíclica de San Juan XXIII sobre la paz: "La paz en la tierra, anhelo profundo de todos los hombres de buena voluntad, no puede establecerse ni consolidarse si no se respetan fielmente el orden establecido por Dios". A los católicos la dirigió "y a todos los hombres de buena voluntad".',
    src: 'vatican.va · Juan XXIII',
    link: 'https://www.vatican.va/content/john-xxiii/es/encyclicals/documents/hf_j-xxiii_enc_11041963_pacem.html',
  },
  {
    id: 'doc-populorum',
    cat: 'Documentos',
    ico: '📜',
    color: '#1F5F8F',
    title: 'Populorum Progressio (1967)',
    body: 'Encíclica de Pablo VI sobre el desarrollo de los pueblos: "El desarrollo de los pueblos, sobre todo de aquellos que luchan por liberarse del yugo del hambre, de la miseria, de las enfermedades endémicas y de la ignorancia, debe ser considerado como la transición de condiciones de vida menos humanas a condiciones más humanas".',
    src: 'vatican.va · Pablo VI',
    link: 'https://www.vatican.va/content/paul-vi/es/encyclicals/documents/hf_p-vi_enc_26031967_populorum.html',
  },
  {
    id: 'doc-eg',
    cat: 'Documentos',
    ico: '💛',
    color: '#1F5F8F',
    title: 'Evangelii Gaudium (2013)',
    body: 'Exhortación apostólica del Papa Francisco sobre el anuncio del Evangelio. Comienza con un llamado: "La alegría del Evangelio llena el corazón y la vida entera de los que se encuentran con Jesús. Quienes se dejan salvar por Él son liberados del pecado, de la tristeza, del vacío interior y del aislamiento".',
    src: 'vatican.va · Francisco',
    link: 'https://www.vatican.va/content/francesco/es/apost_exhortations/documents/papa-francesco_esortazione-ap_20131124_evangelii-gaudium.html',
  },
  {
    id: 'doc-caritas',
    cat: 'Documentos',
    ico: '📜',
    color: '#1F5F8F',
    title: 'Caritas in Veritate (2009)',
    body: 'Encíclica de Benedicto XVI: "La caridad en la verdad, de la que Jesucristo se ha hecho testigo con su vida terrena y, sobre todo, con su muerte y resurrección, es la principal fuerza impulsora del auténtico desarrollo de cada persona y de toda la humanidad".',
    src: 'vatican.va · Benedicto XVI',
    link: 'https://www.vatican.va/content/benedict-xvi/es/encyclicals/documents/hf_ben-xvi_enc_20090629_caritas-in-veritate.html',
  },
  {
    id: 'doc-cv',
    cat: 'Documentos',
    ico: '🔆',
    color: '#1F5F8F',
    title: 'Christus Vivit (2019)',
    body: 'Exhortación apostólica postsinodal del Papa Francisco a los jóvenes y a todo el pueblo de Dios. Comienza: "«Cristo vive. Él es nuestra esperanza, y la más hermosa juventud de este mundo». Todo lo que toca Él se vuelve joven, se vuelve nuevo, se llena de vida y de sentido".',
    src: 'vatican.va · Francisco',
    link: 'https://www.vatican.va/content/francesco/es/apost_exhortations/documents/papa-francesco_esortazione-ap_20190325_christus-vivit.html',
  },
  {
    id: 'doc-dv',
    cat: 'Documentos',
    ico: '✝️',
    color: '#1F5F8F',
    title: 'Dei Verbum (1965)',
    body: 'Constitución dogmática del Concilio Vaticano II sobre la divina Revelación: "Dios, que habita una luz inaccesible, quiso revelarse a sí mismo y dar a conocer el misterio de su voluntad, por el cual los hombres tienen acceso al Padre en el Espïritu Santo y participan de la naturaleza divina".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651118_dei-verbum_sp.html',
  },

  /* ---- Más documentos tomados de los catálogos oficiales de vatican.va ---- */

  {
    id: 'dc-ft',
    cat: 'Documentos',
    ico: '🕊️',
    color: '#1F5F8F',
    title: 'Fratelli Tutti (2020)',
    body: '"«Fratelli tutti», escribía san Francisco de Asís para dirigirse a todos los hermanos y las hermanas y proponerles una forma de vida con sabor a Evangelio." Con esa encíclica (4-X-2020) el Papa Francisco propone la fraternidad universal y la amistad social para curar las heridas del mundo.',
    src: 'vatican.va · Francisco',
    link: 'https://www.vatican.va/content/francesco/es/encyclicals/documents/papa-francesco_20201003_enciclica-fratelli-tutti.html',
  },
  {
    id: 'dc-dilexit',
    cat: 'Documentos',
    ico: '❤️',
    color: '#1F5F8F',
    title: 'Dilexit Nos (2024)',
    body: '"«Nos amó», dice san Pablo refiriéndose a Cristo (Rm 8, 37), para ayudarnos a descubrir que de ese amor nada «podrá separarnos» (Rm 8, 39)." Así comienza la encíclica Dilexit Nos (24-X-2024) del Papa Francisco sobre el amor humano y divino del Corazón de Jesucristo.',
    src: 'vatican.va · Francisco',
    link: 'https://www.vatican.va/content/francesco/es/encyclicals/documents/20241024-enciclica-dilexit-nos.html',
  },
  {
    id: 'dc-lumen-fidei',
    cat: 'Documentos',
    ico: '🕯️',
    color: '#1F5F8F',
    title: 'Lumen Fidei (2013)',
    body: '"La luz de la fe": así expresa la tradición de la Iglesia el gran don traído por Jesús. Primera encíclica del Papa Francisco (29-VI-2013), publicada en el Año de la Fe y comenzada junto a Benedicto XVI: la fe ilumina y guía el camino de la vida.',
    src: 'vatican.va · Francisco',
    link: 'https://www.vatican.va/content/francesco/es/encyclicals/documents/papa-francesco_20130629_enciclica-lumen-fidei.html',
  },
  {
    id: 'dc-spe-salvi',
    cat: 'Documentos',
    ico: '🌅',
    color: '#1F5F8F',
    title: 'Spe Salvi (2007)',
    body: '«Spe salvi facti sumus» —en esperanza fuimos salvados—, dice san Pablo a los Romanos y también a nosotros (Rm 8, 24). Así comienza la segunda encíclica de Benedicto XVI (30-XI-2007), dedicada a la esperanza cristiana.',
    src: 'vatican.va · Benedicto XVI',
    link: 'https://www.vatican.va/content/benedict-xvi/es/encyclicals/documents/hf_ben-xvi_enc_20071130_spe-salvi.html',
  },
  {
    id: 'dc-deus-caritas',
    cat: 'Documentos',
    ico: '❤️',
    color: '#1F5F8F',
    title: 'Deus Caritas Est (2005)',
    body: '"«Dios es amor, y quien permanece en el amor permanece en Dios y Dios en él» (1 Jn 4, 16). Estas palabras de la Primera carta de Juan expresan con claridad meridiana el corazón de la fe cristiana." Así abre su primera encíclica Benedicto XVI (25-XII-2005): el amor, eros y caridad, es la fuerza del cristiano.',
    src: 'vatican.va · Benedicto XVI',
    link: 'https://www.vatican.va/content/benedict-xvi/es/encyclicals/documents/hf_ben-xvi_enc_20051225_deus-caritas-est.html',
  },
  {
    id: 'dc-rh',
    cat: 'Documentos',
    ico: '🕊️',
    color: '#1F5F8F',
    title: 'Redemptor Hominis (1979)',
    body: '"El Redentor del hombre, Jesucristo, es el centro del cosmos y de la historia." Así comienza la primera encíclica de San Juan Pablo II (4-III-1979), publicada pocos meses después de su elección, sobre la redención y la dignidad del hombre.',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/encyclicals/documents/hf_jp-ii_enc_04031979_redemptor-hominis.html',
  },
  {
    id: 'dc-dim',
    cat: 'Documentos',
    ico: '🌊',
    color: '#1F5F8F',
    title: 'Dives in Misericordia (1980)',
    body: '"«Dios rico en misericordia» es el que Jesucristo nos ha revelado como Padre; cabalmente su Hijo, en sí mismo, nos lo ha manifestado y nos lo ha hecho conocer." Segunda encíclica de San Juan Pablo II (30-XI-1980), centrada en la misericordia divina.',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/encyclicals/documents/hf_jp-ii_enc_30111980_dives-in-misericordia.html',
  },
  {
    id: 'dc-le',
    cat: 'Documentos',
    ico: '🔨',
    color: '#1F5F8F',
    title: 'Laborem Exercens (1981)',
    body: '"Con su trabajo el hombre ha de procurarse el pan cotidiano, contribuir al continuo progreso de las ciencias y la técnica y, sobre todo, a la incesante elevación cultural y moral de la sociedad." Encíclica social de San Juan Pablo II (14-IX-1981) sobre el trabajo humano.',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/encyclicals/documents/hf_jp-ii_enc_14091981_laborem-exercens.html',
  },
  {
    id: 'dc-ca',
    cat: 'Documentos',
    ico: '🌾',
    color: '#1F5F8F',
    title: 'Centesimus Annus (1991)',
    body: 'Encíclica promulgada el 1-V-1991, a los cien años de Rerum Novarum. San Juan Pablo II recuerda que la rica savia de aquella raíz no se ha agotado y actualiza la doctrina social de la Iglesia para la nueva época, tras la caída de los regímenes totalitarios.',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/encyclicals/documents/hf_jp-ii_enc_01051991_centesimus-annus.html',
  },
  {
    id: 'dc-ev',
    cat: 'Documentos',
    ico: '🧬',
    color: '#1F5F8F',
    title: 'Evangelium Vitae (1995)',
    body: '"El Evangelio de la vida está en el centro del mensaje de Jesús. Acogido con amor cada día por la Iglesia, es anunciado con intrépida fidelidad como buena noticia a los hombres de todas las épocas y culturas." Encíclica de San Juan Pablo II (25-III-1995) sobre el don y el valor de la vida.',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/encyclicals/documents/hf_jp-ii_enc_25031995_evangelium-vitae.html',
  },
  {
    id: 'dc-vs',
    cat: 'Documentos',
    ico: '💡',
    color: '#1F5F8F',
    title: 'Veritatis Splendor (1993)',
    body: '"El esplendor de la verdad brilla en todas las obras del Creador y, de modo particular, en el hombre, creado a imagen y semejanza de Dios." Así comienza la encíclica (6-VIII-1993) de San Juan Pablo II sobre la enseñanza moral fundamental de la Iglesia.',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/encyclicals/documents/hf_jp-ii_enc_06081993_veritatis-splendor.html',
  },
  {
    id: 'dc-fr',
    cat: 'Documentos',
    ico: '🦋',
    color: '#1F5F8F',
    title: 'Fides et Ratio (1998)',
    body: '"La fe y la razón (Fides et ratio) son como las dos alas con las cuales el espíritu humano se eleva hacia la contemplación de la verdad." Así comienza la encíclica de San Juan Pablo II (14-IX-1998) sobre las relaciones entre fe y razón.',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/encyclicals/documents/hf_jp-ii_enc_14091998_fides-et-ratio.html',
  },
  {
    id: 'dc-mm',
    cat: 'Documentos',
    ico: '🌍',
    color: '#1F5F8F',
    title: 'Mater et Magistra (1961)',
    body: '"Madre y Maestra de pueblos, la Iglesia católica fue fundada como tal por Jesucristo para que, en el transcurso de los siglos, encontraran su salvación todos cuantos habían de entrar." Encíclica de San Juan XXIII (15-V-1961) sobre la cuestión social a la luz de la doctrina cristiana.',
    src: 'vatican.va · Juan XXIII',
    link: 'https://www.vatican.va/content/john-xxiii/es/encyclicals/documents/hf_j-xxiii_enc_15051961_mater.html',
  },
  {
    id: 'dc-es',
    cat: 'Documentos',
    ico: '🗺️',
    color: '#1F5F8F',
    title: 'Ecclesiam Suam (1964)',
    body: '"El esfuerzo orientado al anuncio del Evangelio a los hombres de nuestro tiempo, exaltados por la esperanza pero a la vez perturbados con frecuencia por el temor y la angustia, es sin duda alguna un servicio..." Primera encíclica de Pablo VI (6-VIII-1964), sobre los caminos de la Iglesia.',
    src: 'vatican.va · Pablo VI',
    link: 'https://www.vatican.va/content/paul-vi/es/encyclicals/documents/hf_p-vi_enc_06081964_ecclesiam.html',
  },
  {
    id: 'dc-mc',
    cat: 'Documentos',
    ico: '🌹',
    color: '#1F5F8F',
    title: 'Marialis Cultus (1974)',
    body: '"Desde que fuimos elegidos a la Cátedra de Pedro, hemos puesto constante cuidado en incrementar el culto mariano." Exhortación apostólica de Pablo VI (2-II-1974) sobre el lugar que corresponde al culto de la Santísima Virgen María en la liturgia.',
    src: 'vatican.va · Pablo VI',
    link: 'https://www.vatican.va/content/paul-vi/es/apost_exhortations/documents/hf_p-vi_exh_19740202_marialis-cultus.html',
  },
  {
    id: 'dc-en',
    cat: 'Documentos',
    ico: '📯',
    color: '#1F5F8F',
    title: 'Evangelii Nuntiandi (1975)',
    body: 'Exhortación apostólica de Pablo VI (8-XII-1975) sobre la evangelización en el mundo contemporáneo, considerada el testamento evangelizador del pontífice: anunciar el Evangelio es la vocación propia de la Iglesia.',
    src: 'vatican.va · Pablo VI',
    link: 'https://www.vatican.va/content/paul-vi/es/apost_exhortations/documents/hf_p-vi_exh_19751208_evangelii-nuntiandi.html',
  },
  {
    id: 'dc-sc2',
    cat: 'Documentos',
    ico: '🍞',
    color: '#1F5F8F',
    title: 'Sacramentum Caritatis (2007)',
    body: 'Exhortación apostólica postsinodal de Benedicto XVI (22-II-2007) sobre la Eucaristía, fuente y cumbre de la vida y de la misión de la Iglesia. Recoge los trabajos del Sínodo de los Obispos sobre la Eucaristía celebrado en 2005.',
    src: 'vatican.va · Benedicto XVI',
    link: 'https://www.vatican.va/content/benedict-xvi/es/apost_exhortations/documents/hf_ben-xvi_exh_20070222_sacramentum-caritatis.html',
  },
  {
    id: 'dc-vd',
    cat: 'Documentos',
    ico: '📖',
    color: '#1F5F8F',
    title: 'Verbum Domini (2010)',
    body: 'Exhortación apostólica postsinodal de Benedicto XVI (30-IX-2010) sobre la Palabra de Dios en la vida y en la misión de la Iglesia, fruto del Sínodo de los Obispos dedicado a la Palabra en 2008.',
    src: 'vatican.va · Benedicto XVI',
    link: 'https://www.vatican.va/content/benedict-xvi/es/apost_exhortations/documents/hf_ben-xvi_exh_20100930_verbum-domini.html',
  },
  {
    id: 'dc-am',
    cat: 'Documentos',
    ico: '🗣️',
    color: '#1F5F8F',
    title: 'Africae Munus (2011)',
    body: 'Exhortación apostólica postsinodal de Benedicto XVI (19-XI-2011) sobre la Iglesia en África al servicio de la reconciliación, la justicia y la paz. Arranca con la promesa: "Ahora hago nuevas todas las cosas" (Ap 21, 5).',
    src: 'vatican.va · Benedicto XVI',
    link: 'https://www.vatican.va/content/benedict-xvi/es/apost_exhortations/documents/hf_ben-xvi_exh_20111119_africae-munus.html',
  },
  {
    id: 'dc-gov',
    cat: 'Documentos',
    ico: '✨',
    color: '#1F5F8F',
    title: 'Gaudete et Exsultate (2018)',
    body: '"Alegraos y regocijaos": así comienza la exhortación apostólica del Papa Francisco (19-III-2018) sobre la llamada a la santidad en el mundo actual, que rescata a "los santos de la puerta de al lado".',
    src: 'vatican.va · Francisco',
    link: 'https://www.vatican.va/content/francesco/es/apost_exhortations/documents/papa-francesco_esortazione-ap_20180319_gaudete-et-exsultate.html',
  },
  {
    id: 'dc-al',
    cat: 'Documentos',
    ico: '👨‍👩‍👧',
    color: '#1F5F8F',
    title: 'Amoris Laetitia (2016)',
    body: '"La alegría del amor que se vive en las familias es también el júbilo de la Iglesia." Así comienza la exhortación apostólica postsinodal del Papa Francisco (19-III-2016) sobre el amor en la familia.',
    src: 'vatican.va · Francisco',
    link: 'https://www.vatican.va/content/francesco/es/apost_exhortations/documents/papa-francesco_esortazione-ap_20160319_amoris-laetitia.html',
  },
  {
    id: 'dc-qa',
    cat: 'Documentos',
    ico: '🌳',
    color: '#1F5F8F',
    title: 'Querida Amazonia (2020)',
    body: '"La querida Amazonia se muestra ante el mundo con todo su esplendor, su drama, su misterio." Exhortación apostólica postsinodal del Papa Francisco (2-II-2020) sobre la Iglesia y la ecología integral en la región amazónica.',
    src: 'vatican.va · Francisco',
    link: 'https://www.vatican.va/content/francesco/es/apost_exhortations/documents/papa-francesco_esortazione-ap_20200202_querida-amazonia.html',
  },
  {
    id: 'dc-clc',
    cat: 'Documentos',
    ico: '🌹',
    color: '#1F5F8F',
    title: 'C’est la Confiance (2023)',
    body: '"«La confianza, y nada más que la confianza, puede conducirnos al Amor»." Exhortación apostólica del Papa Francisco (15-X-2023), publicada en el 150 aniversario del nacimiento de Santa Teresa del Niño Jesús, Doctora de la Iglesia.',
    src: 'vatican.va · Francisco',
    link: 'https://www.vatican.va/content/francesco/es/apost_exhortations/documents/20231015-santateresa-delbambinogesu.html',
  },
  {
    id: 'dc-fd',
    cat: 'Documentos',
    ico: '📚',
    color: '#1F5F8F',
    title: 'Fidei Depositum (1992)',
    body: '"Conservar el depósito de la fe es la misión que el Señor confió a su Iglesia y que ella realiza en todo tiempo." Constitución apostólica (11-X-1992) con la que San Juan Pablo II promulgó el Catecismo de la Iglesia Católica.',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/apost_constitutions/documents/hf_jp-ii_apc_19921011_fidei-depositum.html',
  },
  {
    id: 'dc-cl',
    cat: 'Documentos',
    ico: '👥',
    color: '#1F5F8F',
    title: 'Christifideles Laici (1988)',
    body: '"Los fieles laicos, cuya vocación y misión en la Iglesia y en el mundo a los veinte años del Concilio Vaticano II ha sido el tema del Sínodo de los Obispos de 1987, pertenecen a aquel Pueblo de Dios representado en los obreros de la viña." Exhortación postsinodal de San Juan Pablo II (30-XII-1988).',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/apost_exhortations/documents/hf_jp-ii_exh_30121988_christifideles-laici.html',
  },
  {
    id: 'dc-ct',
    cat: 'Documentos',
    ico: '🎓',
    color: '#1F5F8F',
    title: 'Catechesi Tradendae (1979)',
    body: '"La catequesis ha sido siempre considerada por la Iglesia como una de sus tareas primordiales, ya que Cristo resucitado, antes de volver al Padre, dio a los Apóstoles esta última consigna: hacer discípulos a todas las gentes." Exhortación de San Juan Pablo II (16-X-1979) sobre la catequesis en nuestro tiempo.',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/apost_exhortations/documents/hf_jp-ii_exh_16101979_catechesi-tradendae.html',
  },
  {
    id: 'dc-ee',
    cat: 'Documentos',
    ico: '🍞',
    color: '#1F5F8F',
    title: 'Ecclesia de Eucharistia (2003)',
    body: '"La Iglesia vive de la Eucaristía. Esta verdad no expresa solamente una experiencia cotidiana de fe, sino que encierra en síntesis el núcleo del misterio de la Iglesia." Carta encíclica de San Juan Pablo II (17-IV-2003).',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/encyclicals/documents/hf_jp-ii_enc_20030417_eccl-de-euch.html',
  },
  {
    id: 'dc-rm',
    cat: 'Documentos',
    ico: '🌙',
    color: '#1F5F8F',
    title: 'Redemptoris Mater (1987)',
    body: '"La misión de Cristo Redentor, confiada a la Iglesia, está aún lejos de cumplirse." Así comienza la encíclica de San Juan Pablo II (25-III-1987) sobre la Santísima Virgen María en la vida de la Iglesia peregrina.',
    src: 'vatican.va · Juan Pablo II',
    link: 'https://www.vatican.va/content/john-paul-ii/es/encyclicals/documents/hf_jp-ii_enc_25031987_redemptoris-mater.html',
  },

  /* ---- Los 16 documentos del Concilio Vaticano II ---- */

  {
    id: 'dc-im',
    cat: 'Documentos',
    ico: '📡',
    color: '#1F5F8F',
    title: 'Inter Mirifica (1963)',
    body: 'Decreto del Concilio Vaticano II (4-XII-1963) sobre los medios de comunicación social: "Entre los maravillosos inventos de la técnica que, sobre todo en estos tiempos, el ingenio humano, con la ayuda de Dios, ha extraído de las cosas creadas, la madre Iglesia acoge y fomenta aquellos que se refieren principalmente al espíritu humano".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19631204_inter-mirifica_sp.html',
  },
  {
    id: 'dc-oe',
    cat: 'Documentos',
    ico: '⛪',
    color: '#1F5F8F',
    title: 'Orientalium Ecclesiarum (1964)',
    body: 'Decreto del Vaticano II (21-XI-1964) sobre las Iglesias orientales católicas: la Iglesia "tiene en gran aprecio las instituciones, los ritos litúrgicos, las tradiciones eclesiásticas y la disciplina de la vida cristiana de las Iglesias orientales".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19641121_orientalium-ecclesiarum_sp.html',
  },
  {
    id: 'dc-ur',
    cat: 'Documentos',
    ico: '🤝',
    color: '#1F5F8F',
    title: 'Unitatis Redintegratio (1964)',
    body: 'Decreto conciliar (21-XI-1964) sobre el ecumenismo: "Promover la restauración de la unidad entre todos los cristianos es uno de los fines principales que se ha propuesto el Sacrosanto Concilio Vaticano II".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19641121_unitatis-redintegratio_sp.html',
  },
  {
    id: 'dc-cd',
    cat: 'Documentos',
    ico: '⛪',
    color: '#1F5F8F',
    title: 'Christus Dominus (1965)',
    body: 'Decreto (28-X-1965) sobre el ministerio pastoral de los obispos: "Cristo Señor, Hijo de Dios vivo, que vino a salvar del pecado a su pueblo y a santificar a todos los hombres, como Él fue enviado por el Padre, así también envió a sus Apóstoles".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19651028_christus-dominus_sp.html',
  },
  {
    id: 'dc-pc',
    cat: 'Documentos',
    ico: '🌿',
    color: '#1F5F8F',
    title: 'Perfectae Caritatis (1965)',
    body: 'Decreto (28-X-1965) sobre la renovación de la vida religiosa: la prosecución de la caridad perfecta por la práctica de los consejos evangélicos tiene su origen en la doctrina y en los ejemplos del Divino Maestro.',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19651028_perfectae-caritatis_sp.html',
  },
  {
    id: 'dc-ot',
    cat: 'Documentos',
    ico: '📿',
    color: '#1F5F8F',
    title: 'Optatam Totius (1965)',
    body: 'Decreto (28-X-1965) sobre la formación sacerdotal: "la anhelada renovación de toda la Iglesia depende en gran parte del ministerio de los sacerdotes" y por eso "proclama la grandísima importancia de la formación sacerdotal".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19651028_optatam-totius_sp.html',
  },
  {
    id: 'dc-aa',
    cat: 'Documentos',
    ico: '🌱',
    color: '#1F5F8F',
    title: 'Apostolicam Actuositatem (1965)',
    body: 'Decreto (18-XI-1965) sobre el apostolado de los laicos: "Queriendo intensificar más la actividad apostólica del Pueblo de Dios, el Santo Concilio se dirige solícitamente a los cristianos seglares".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19651118_apostolicam-actuositatem_sp.html',
  },
  {
    id: 'dc-ag',
    cat: 'Documentos',
    ico: '🌐',
    color: '#1F5F8F',
    title: 'Ad Gentes (1965)',
    body: 'Decreto (7-XII-1965) sobre la actividad misionera de la Iglesia: "La Iglesia, enviada por Dios a las gentes para ser el sacramento universal de la salvación, obedeciendo el mandato de su Fundador, se esfuerza en anunciar el Evangelio".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19651207_ad-gentes_sp.html',
  },
  {
    id: 'dc-po',
    cat: 'Documentos',
    ico: '🕯️',
    color: '#1F5F8F',
    title: 'Presbyterorum Ordinis (1965)',
    body: 'Decreto (7-XII-1965) sobre el ministerio y la vida de los presbíteros: "Repetidas veces ha traído este Sagrado Concilio a la memoria de todos la excelencia del Orden de los presbíteros en la Iglesia".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19651207_presbyterorum-ordinis_sp.html',
  },
  {
    id: 'dc-ge',
    cat: 'Documentos',
    ico: '🏫',
    color: '#1F5F8F',
    title: 'Gravissimum Educationis (1965)',
    body: 'Declaración (28-X-1965) sobre la educación cristiana: "El Santo Concilio Ecuménico considera atentamente la importancia decisiva de la educación en la vida del hombre y su influjo cada vez mayor en el progreso social contemporáneo".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decl_19651028_gravissimum-educationis_sp.html',
  },
  {
    id: 'dc-na',
    cat: 'Documentos',
    ico: '🕊️',
    color: '#1F5F8F',
    title: 'Nostra Aetate (1965)',
    body: 'Declaración (28-X-1965) sobre la relación de la Iglesia con las religiones no cristianas: "En nuestra época, en la que el género humano se une cada vez más estrechamente, la Iglesia considera con mayor atención cuál es su relación con las religiones no cristianas".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decl_19651028_nostra-aetate_sp.html',
  },
  {
    id: 'dc-dh',
    cat: 'Documentos',
    ico: '🪶',
    color: '#1F5F8F',
    title: 'Dignitatis Humanae (1965)',
    body: 'Declaración (7-XII-1965) sobre la libertad religiosa: "Los hombres de nuestro tiempo se hacen cada vez más conscientes de la dignidad de la persona humana" y exigen "que los hombres en su actuación gocen y usen del propio criterio y libertad responsable".',
    src: 'vatican.va · Concilio Vaticano II',
    link: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decl_19651207_dignitatis-humanae_sp.html',
  },

  /* ---- Catequesis de las Audiencias Generales del Papa Francisco ---- */

  {
    id: 'dc-au1',
    cat: 'Documentos',
    ico: '🗣️',
    color: '#1F5F8F',
    title: 'Catequesis: la Semana Santa',
    body: 'En su primera audiencia general (27-III-2013) el Papa Francisco reflexionó: "¿Qué significa seguir a Jesús en su camino al Calvario hacia la Cruz y la Resurrección?" Y recordó que "Dios es así: Él da siempre el primer paso, Él se mueve hacia nosotros".',
    src: 'vatican.va · Audiencias del Papa Francisco',
    link: 'https://www.vatican.va/content/francesco/es/audiences.html',
  },
  {
    id: 'dc-au2',
    cat: 'Documentos',
    ico: '☁️',
    color: '#1F5F8F',
    title: 'Catequesis: la Ascensión',
    body: 'Catequesis del Papa Francisco: "En el Credo encontramos afirmado que Jesús «subió al cielo y está sentado a la derecha del Padre». La vida terrena de Jesús culmina con el acontecimiento de la Ascensión, es decir, cuando Él pasa de este mundo al Padre".',
    src: 'vatican.va · Audiencias del Papa Francisco',
    link: 'https://www.vatican.va/content/francesco/es/audiences.html',
  },
  {
    id: 'dc-au3',
    cat: 'Documentos',
    ico: '💡',
    color: '#1F5F8F',
    title: 'Catequesis: el Espíritu y la verdad',
    body: '"El Espíritu Santo «os guiará hasta la verdad» (Jn 16, 13)." En su catequesis, el Papa Francisco enseñó que "la verdad no se aferra como una cosa, la verdad se encuentra. No es una posesión, es un encuentro con una Persona".',
    src: 'vatican.va · Audiencias del Papa Francisco',
    link: 'https://www.vatican.va/content/francesco/es/audiences.html',
  },
  {
    id: 'dc-au4',
    cat: 'Documentos',
    ico: '⛪',
    color: '#1F5F8F',
    title: 'Catequesis: la Iglesia, templo',
    body: '"La Iglesia es la «casa de Dios», el lugar de su presencia, donde podemos hallar y encontrar al Señor; la Iglesia es el Templo en el que habita el Espíritu Santo que la anima, la guía y la sostiene." Catequesis del Papa Francisco sobre el misterio de la Iglesia.',
    src: 'vatican.va · Audiencias del Papa Francisco',
    link: 'https://www.vatican.va/content/francesco/es/audiences.html',
  },
  {
    id: 'dc-au5',
    cat: 'Documentos',
    ico: '🌟',
    color: '#1F5F8F',
    title: 'Catequesis: la Iglesia es santa',
    body: '"¿Cómo puede ser santa una Iglesia formada por seres humanos, por pecadores?", preguntó el Papa Francisco. Y respondió con san Pablo: "Cristo amó a su Iglesia y se entregó a sí mismo por ella, para hacerla santa" (Ef 5, 25-26). No somos nosotros quienes la hacemos santa.',
    src: 'vatican.va · Audiencias del Papa Francisco',
    link: 'https://www.vatican.va/content/francesco/es/audiences.html',
  },
  {
    id: 'dc-au6',
    cat: 'Documentos',
    ico: '🤝',
    color: '#1F5F8F',
    title: 'Catequesis: la comunión de los santos',
    body: '"No estamos solos, sino que existe una comunión de vida entre todos aquellos que pertenecen a Cristo." En esta catequesis el Papa Francisco explica que la comunión de los santos nace de la fe y se alimenta de los sacramentos, los carismas y la caridad.',
    src: 'vatican.va · Audiencias del Papa Francisco',
    link: 'https://www.vatican.va/content/francesco/es/audiences.html',
  },
  {
    id: 'dc-au7',
    cat: 'Documentos',
    ico: '🗝️',
    color: '#1F5F8F',
    title: 'Catequesis: el perdón de los pecados',
    body: 'El Papa Francisco enseñó que "el protagonista del perdón de los pecados es el Espíritu Santo", el mismo que Jesús comunicó a los Apóstoles cuando les entregó el poder de las llaves: "A quienes les perdonéis los pecados, les quedan perdonados" (Jn 20, 22-23).',
    src: 'vatican.va · Audiencias del Papa Francisco',
    link: 'https://www.vatican.va/content/francesco/es/audiences.html',
  },
  {
    id: 'dc-au8',
    cat: 'Documentos',
    ico: '🌅',
    color: '#1F5F8F',
    title: 'Catequesis: la resurrección de la carne',
    body: '"Nuestra resurrección está estrechamente relacionada con la resurrección de Jesús. El hecho de que Él resucitó es la prueba de que existe la resurrección de los muertos", explicó el Papa Francisco, recordando las palabras de Jesús: "Yo soy la resurrección y la vida" (Jn 11, 25).',
    src: 'vatican.va · Audiencias del Papa Francisco',
    link: 'https://www.vatican.va/content/francesco/es/audiences.html',
  },
];